apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: portfolio
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: '{"nginx":["web"]}'
    spec:
      containers:
        - image: ${{GCP_REGISTRY}}/nginx
          name: nginx
          ports:
            - containerPort: 80
        - image: ${{GCP_REGISTRY}}/web
          name: web
          ports:
            - containerPort: 3000
