name: CI

env:
  TZ: Asia/Tokyo

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: pnpm setup composite
        uses: ./.github/actions/pnpm-setup

      - name: Install Deps
        run: pnpm install --frozen-lockfile

  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v3

      - name: pnpm setup composite
        uses: ./.github/actions/pnpm-setup

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint
