name: CI

on: pull_request

env:
  TZ: Asia/Tokyo
  NODE_VERSION: 21.7.3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: pnpm setup composite
        uses: ./.github/actions/pnpm-setup

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint
