name: CI

env:
  TZ: Asia/Tokyo

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      # https://cloud.google.com/blog/ja/products/identity-security/enabling-keyless-authentication-from-github-actions
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: "beta"

      - name: Docker use gcloud CLI as credential helper
        run: gcloud auth configure-docker asia-north1-docker.pkg.dev

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Build
        run: docker build -t ${{secrets.GCP_REGISTRY}}:$GITHUB_SHA .

      - name: Push
        run: docker push ${{secrets.GCP_REGISTRY}}:$GITHUB_SHA

  # setup:
  #   name: Setup
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: pnpm setup composite
  #       uses: ./.github/actions/pnpm-setup

  #     - name: Install Deps
  #       run: pnpm install --frozen-lockfile

  # build-and-lint:
  #   name: Build and Lint
  #   runs-on: ubuntu-latest
  #   needs:
  #     - setup
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: pnpm setup composite
  #       uses: ./.github/actions/pnpm-setup

  #     - name: build
  #       run: pnpm build

  #     - name: lint
  #       run: pnpm lint
