name: Production Deploy

env:
  TZ: Asia/Tokyo

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: pnpm setup composite
        uses: ./.github/actions/pnpm-setup

      - name: Install Deps
        run: pnpm install --frozen-lockfile
