name: Deploy

on:
  push:
    branches:
      - main

env:
  TZ: Asia/Tokyo
  NODE_VERSION: 21.7.3
  PNPM_VERSION: 9.9.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: enable corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: deploy to Cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 0xjj
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
