export type Category = 'tool' | 'game' | 'ui';

export interface Tool {
  slug: string;
  name: string;
  description: string;
  href: string;
  category: Category;
}

export const categories: { value: Category; label: string }[] = [
  { value: 'tool', label: 'Tools' },
  { value: 'game', label: 'Games' },
  { value: 'ui', label: 'UI Lab' },
];

export const tools: Tool[] = [
  // ── Tools (A→Z) ──
  {
    slug: 'base64',
    name: 'Base64 Encoder / Decoder',
    description: 'テキストをBase64にエンコード、またはBase64をテキストにデコードします。',
    href: '/base64/',
    category: 'tool',
  },
  {
    slug: 'case',
    name: 'Case Converter',
    description: 'camelCase・PascalCase・snake_case・kebab-case・UPPER_SNAKE_CASE を相互変換します。',
    href: '/case/',
    category: 'tool',
  },
  {
    slug: 'color',
    name: 'Color Converter',
    description: 'HEX・RGB・HSL・OKLAB・OKLCH など、あらゆるCSS色形式を相互変換します。',
    href: '/color/',
    category: 'tool',
  },
  {
    slug: 'cron',
    name: 'Cron Expression Parser',
    description: 'cron式を解析し、次回以降の実行予定時刻をプレビューします。',
    href: '/cron/',
    category: 'tool',
  },
  {
    slug: 'css-specificity',
    name: 'CSS Specificity Calculator',
    description: 'CSSセレクタの詳細度 (a, b, c) を計算・比較します。',
    href: '/css-specificity/',
    category: 'tool',
  },
  {
    slug: 'easing',
    name: 'Easing Visualizer',
    description: 'CSS用のcubic-bezierイージングカーブを視覚的にプレビューします。',
    href: '/easing/',
    category: 'tool',
  },
  {
    slug: 'exif',
    name: 'EXIF Viewer',
    description: '画像やPDFに埋め込まれたメタデータ（EXIF・XMP・IPTC）を表示します。',
    href: '/exif/',
    category: 'tool',
  },
  {
    slug: 'gitignore',
    name: '.gitignore Generator',
    description: 'gitignore.io APIを使って、プロジェクトに合った .gitignore を生成します。',
    href: '/gitignore/',
    category: 'tool',
  },
  {
    slug: 'hash',
    name: 'Hash Calculator',
    description: 'テキストのSHA-1・SHA-256・SHA-384・SHA-512ハッシュ値を計算します。',
    href: '/hash/',
    category: 'tool',
  },
  {
    slug: 'html-entity',
    name: 'HTML Entity Encoder / Decoder',
    description: '特殊文字をHTMLエンティティにエンコード、またはデコードします。',
    href: '/html-entity/',
    category: 'tool',
  },
  {
    slug: 'http-status',
    name: 'HTTP Status Codes',
    description: 'HTTPステータスコードをカテゴリ別に一覧・検索できます。',
    href: '/http-status/',
    category: 'tool',
  },
  {
    slug: 'grpc-status',
    name: 'gRPC Status Codes',
    description: 'gRPCステータスコードをHTTP対応表と説明付きで一覧できます。',
    href: '/grpc-status/',
    category: 'tool',
  },
  {
    slug: 'httpinspector',
    name: 'HTTP Inspector',
    description: '任意のURLのHTTPレスポンスヘッダー・ボディプレビュー・DNSレコードを確認します。',
    href: '/httpinspector/',
    category: 'tool',
  },
  {
    slug: 'json',
    name: 'JSON Formatter',
    description: 'JSONの整形・バリデーションを行い、構文エラーを表示します。',
    href: '/json/',
    category: 'tool',
  },
  {
    slug: 'json-to-ts',
    name: 'JSON to TypeScript',
    description: 'JSONからTypeScriptの型定義を生成します。ネストしたオブジェクトや配列にも対応。',
    href: '/json-to-ts/',
    category: 'tool',
  },
  {
    slug: 'jwt',
    name: 'JWT Decoder',
    description: 'JWTのヘッダー・ペイロード・有効期限をデコードして確認します。',
    href: '/jwt/',
    category: 'tool',
  },
  {
    slug: 'base',
    name: 'Number Base Converter',
    description: '2進数・8進数・10進数・16進数を相互変換します。',
    href: '/base/',
    category: 'tool',
  },
  {
    slug: 'ogp-bg',
    name: 'OGP Background Generator',
    description: '画像から色を抽出し、1200×630のOGP背景画像をブラウザ上で生成します。',
    href: '/ogp-bg/',
    category: 'tool',
  },
  {
    slug: 'ogpchecker',
    name: 'OGP Checker',
    description: '任意のURLのOpen Graph・Twitter Card・メタタグを確認します。',
    href: '/ogpchecker/',
    category: 'tool',
  },
  {
    slug: 'qrcode',
    name: 'QR Code Generator',
    description: 'テキストやURLからQRコードを生成し、PNGでダウンロードできます。',
    href: '/qrcode/',
    category: 'tool',
  },
  {
    slug: 'ratio',
    name: 'Ratio Calculator',
    description: '比率の約分や、既知の比率から不明な値を計算します。',
    href: '/ratio/',
    category: 'tool',
  },
  {
    slug: 'regex',
    name: 'RegEx Tester',
    description: '正規表現をリアルタイムでテストし、マッチ箇所をハイライト表示します。',
    href: '/regex/',
    category: 'tool',
  },
  {
    slug: 'semver',
    name: 'Semver Range Checker',
    description: 'バージョン番号が ^1.2.3 や >=2.0.0 <3.0.0 などのsemver範囲を満たすか判定します。',
    href: '/semver/',
    category: 'tool',
  },
  {
    slug: 'sql',
    name: 'SQL Formatter',
    description: 'SQLクエリを整形・フォーマットします。複数の方言に対応。',
    href: '/sql/',
    category: 'tool',
  },
  {
    slug: 'time-calc',
    name: 'Time Calculator',
    description: 'HH:MM:SS形式の時間を加算・減算して合計を計算します。',
    href: '/time-calc/',
    category: 'tool',
  },
  {
    slug: 'unicode',
    name: 'Unicode Character Search',
    description: 'Unicode文字を名前やコードポイントで検索し、クリップボードにコピーできます。',
    href: '/unicode/',
    category: 'tool',
  },
  {
    slug: 'uuid',
    name: 'UUID Generator',
    description: 'v4 UUIDを一括で即座に生成します。',
    href: '/uuid/',
    category: 'tool',
  },
  // ── UI Lab (A→Z) ──
  {
    slug: 'air-flow',
    name: 'Air Flow',
    description: 'Webカメラの動きをオプティカルフローで検出し、パーティクルが空気のように流されるインタラクティブ可視化。',
    href: '/air-flow/',
    category: 'ui',
  },
  {
    slug: 'audio-reactor',
    name: 'Audio Reactor',
    description: 'マイクの音でレイマーチングされた万華鏡空間が脈動するVJビジュアライゼーション。音が豊かなほど万華鏡が複雑に割れる。',
    href: '/audio-reactor/',
    category: 'ui',
  },
  {
    slug: 'audio-terrain',
    name: 'Audio Terrain',
    description: 'マイクのFFTスペクトルを3D地形に変換し、音楽がリアルタイムで山脈を生成するビジュアライゼーション。',
    href: '/audio-terrain/',
    category: 'ui',
  },
  {
    slug: 'curl-noise',
    name: 'Curl Noise Flow Field',
    description: 'WebGPUコンピュートシェーダーで駆動する、カールノイズベクトル場を流れる数千のパーティクルによる流体的なビジュアル。',
    href: '/curl-noise/',
    category: 'ui',
  },
  {
    slug: 'face-detect',
    name: 'Face Detect Camera',
    description: 'ローカルのWebカメラ映像をcanvasに描画し、OpenCV.jsでブラウザ内だけで顔検出を行います。',
    href: '/face-detect/',
    category: 'ui',
  },
  {
    slug: 'liquid-glass',
    name: 'Liquid Glass',
    description: 'SVGフィルターとbackdrop-filterを使った、Apple風のLiquid Glassエフェクト。',
    href: '/liquid-glass/',
    category: 'ui',
  },
  {
    slug: 'l-system',
    name: 'L-System',
    description: 'リンデンマイヤー書き換え文法とタートルグラフィクスによる手続き的フラクタル生成。',
    href: '/l-system/',
    category: 'ui',
  },
  {
    slug: 'reaction-diffusion',
    name: 'Reaction-Diffusion',
    description: 'WebGPUコンピュートシェーダーでGPU上で動作するGray-Scott反応拡散シミュレーション。',
    href: '/reaction-diffusion/',
    category: 'ui',
  },
  {
    slug: 'mandelbulb',
    name: 'Mandelbulb',
    description: 'WebGPUのレイマーチングで描画する3Dマンデルバルブフラクタル。',
    href: '/mandelbulb/',
    category: 'ui',
  },
  {
    slug: 'lorenz-attractor',
    name: 'Lorenz Attractor',
    description: 'WebGL2フラグメントシェーダーでカラフルな流線として描画するインタラクティブな3Dローレンツアトラクタ。',
    href: '/lorenz-attractor/',
    category: 'ui',
  },
  {
    slug: 'rossler-attractor',
    name: 'Rössler Attractor',
    description: 'WebGL2フラグメントシェーダーでカラフルな流線として描画するインタラクティブな3Dレスラーアトラクタ。',
    href: '/rossler-attractor/',
    category: 'ui',
  },
  {
    slug: 'gyro-card',
    name: 'Gyro Card',
    description: 'スマホの加速度センサーでカードを傾けるインタラクティブな3Dカード体験。',
    href: '/gyro-card/',
    category: 'ui',
  },
  {
    slug: 'tilt-card',
    name: 'Tilt Card',
    description: 'Motionで駆動する、フリップアニメーション付きのインタラクティブな3Dチルトカード。',
    href: '/tilt-card/',
    category: 'ui',
  },
  // ── Games (A→Z) ──
  {
    slug: '2048',
    name: '2048',
    description: 'タイルをスライド・結合して2048を目指す、定番の一人用パズルゲーム。',
    href: '/2048/',
    category: 'game',
  },
  {
    slug: 'connect-four',
    name: 'Connect Four',
    description: 'ディスクを落として縦・横・斜めに4つ並べよう。リアルタイム対戦対応。',
    href: '/connect-four/',
    category: 'game',
  },
  {
    slug: 'dots-and-boxes',
    name: 'Dots & Boxes',
    description: '線を引いてボックスを完成させ、相手より多くのボックスを取ろう。',
    href: '/dots-and-boxes/',
    category: 'game',
  },
  {
    slug: 'reversi',
    name: 'Reversi',
    description: 'ディスクを挟んでひっくり返す定番の戦略ゲーム。リアルタイム対戦対応。',
    href: '/reversi/',
    category: 'game',
  },
  {
    slug: 'tictactoe',
    name: 'Tic-Tac-Toe',
    description: 'リアルタイム対戦の三目並べ。ルームを作ってリンクを共有するだけで対戦開始。',
    href: '/tictactoe/',
    category: 'game',
  },
  {
    slug: 'wordwolf',
    name: 'Word Wolf',
    description: '友達の中に紛れたウルフを見つけ出そう！ 3〜8人で遊べるリアルタイムパーティーゲーム。',
    href: '/wordwolf/',
    category: 'game',
  },
];
