export type Category = 'tool' | 'game' | 'ui';

export interface Tool {
  slug: string;
  name: string;
  description: string;
  href: string;
  category: Category;
}

export const categories: { value: Category; label: string }[] = [
  { value: 'tool', label: 'Tools' },
  { value: 'game', label: 'Games' },
  { value: 'ui', label: 'UI Lab' },
];

export const tools: Tool[] = [
  // ── Tools (A→Z) ──
  {
    slug: 'base64',
    name: 'Base64 Encoder / Decoder',
    description: 'Encode text to Base64 or decode Base64 back to text.',
    href: '/base64/',
    category: 'tool',
  },
  {
    slug: 'case',
    name: 'Case Converter',
    description: 'Convert text between camelCase, PascalCase, snake_case, kebab-case, and UPPER_SNAKE_CASE.',
    href: '/case/',
    category: 'tool',
  },
  {
    slug: 'color',
    name: 'Color Converter',
    description: 'Convert any CSS color format — HEX, RGB, HSL, OKLAB, OKLCH, and more.',
    href: '/color/',
    category: 'tool',
  },
  {
    slug: 'cron',
    name: 'Cron Expression Parser',
    description: 'Parse cron expressions and preview the next scheduled run times.',
    href: '/cron/',
    category: 'tool',
  },
  {
    slug: 'css-specificity',
    name: 'CSS Specificity Calculator',
    description: 'Calculate and compare CSS selector specificity (a, b, c) values.',
    href: '/css-specificity/',
    category: 'tool',
  },
  {
    slug: 'easing',
    name: 'Easing Visualizer',
    description: 'Visualize and preview cubic-bezier easing curves for CSS.',
    href: '/easing/',
    category: 'tool',
  },
  {
    slug: 'exif',
    name: 'EXIF Viewer',
    description: 'View embedded metadata (EXIF, XMP, IPTC) from images and PDF documents.',
    href: '/exif/',
    category: 'tool',
  },
  {
    slug: 'gitignore',
    name: '.gitignore Generator',
    description: 'Generate .gitignore files for your project using the gitignore.io API.',
    href: '/gitignore/',
    category: 'tool',
  },
  {
    slug: 'hash',
    name: 'Hash Calculator',
    description: 'Compute SHA-1, SHA-256, SHA-384, and SHA-512 hashes of any text.',
    href: '/hash/',
    category: 'tool',
  },
  {
    slug: 'html-entity',
    name: 'HTML Entity Encoder / Decoder',
    description: 'Encode special characters to HTML entities or decode them back.',
    href: '/html-entity/',
    category: 'tool',
  },
  {
    slug: 'http-status',
    name: 'HTTP Status Codes',
    description: 'Browse and search HTTP status codes with descriptions by category.',
    href: '/http-status/',
    category: 'tool',
  },
  {
    slug: 'grpc-status',
    name: 'gRPC Status Codes',
    description: 'Browse all gRPC status codes with HTTP equivalents and descriptions.',
    href: '/grpc-status/',
    category: 'tool',
  },
  {
    slug: 'httpinspector',
    name: 'HTTP Inspector',
    description: 'Inspect HTTP response headers, body preview, and DNS records for any URL.',
    href: '/httpinspector/',
    category: 'tool',
  },
  {
    slug: 'json',
    name: 'JSON Formatter',
    description: 'Format and validate JSON with syntax error reporting.',
    href: '/json/',
    category: 'tool',
  },
  {
    slug: 'json-to-ts',
    name: 'JSON to TypeScript',
    description: 'Generate TypeScript interfaces from JSON — handles nested objects and arrays.',
    href: '/json-to-ts/',
    category: 'tool',
  },
  {
    slug: 'jwt',
    name: 'JWT Decoder',
    description: 'Decode and inspect JWT header, payload, and expiry.',
    href: '/jwt/',
    category: 'tool',
  },
  {
    slug: 'base',
    name: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal, and hexadecimal.',
    href: '/base/',
    category: 'tool',
  },
  {
    slug: 'ogp-bg',
    name: 'OGP Background Generator',
    description: 'Extract colors from an image and generate a 1200×630 OGP background — fully in-browser.',
    href: '/ogp-bg/',
    category: 'tool',
  },
  {
    slug: 'ogpchecker',
    name: 'OGP Checker',
    description: 'Inspect Open Graph, Twitter Card, and all meta tags for any URL.',
    href: '/ogpchecker/',
    category: 'tool',
  },
  {
    slug: 'qrcode',
    name: 'QR Code Generator',
    description: 'Generate QR codes from any text or URL and download as PNG.',
    href: '/qrcode/',
    category: 'tool',
  },
  {
    slug: 'ratio',
    name: 'Ratio Calculator',
    description: 'Simplify ratios and calculate missing values from a known ratio.',
    href: '/ratio/',
    category: 'tool',
  },
  {
    slug: 'regex',
    name: 'RegEx Tester',
    description: 'Test regular expressions with live match highlighting.',
    href: '/regex/',
    category: 'tool',
  },
  {
    slug: 'semver',
    name: 'Semver Range Checker',
    description: 'Check if version numbers satisfy a semver range like ^1.2.3 or >=2.0.0 <3.0.0.',
    href: '/semver/',
    category: 'tool',
  },
  {
    slug: 'sql',
    name: 'SQL Formatter',
    description: 'Format and prettify SQL queries with dialect support.',
    href: '/sql/',
    category: 'tool',
  },
  {
    slug: 'time-calc',
    name: 'Time Calculator',
    description: 'Add or subtract HH:MM:SS durations and compute totals.',
    href: '/time-calc/',
    category: 'tool',
  },
  {
    slug: 'unicode',
    name: 'Unicode Character Search',
    description: 'Search Unicode characters by name or code point and copy to clipboard.',
    href: '/unicode/',
    category: 'tool',
  },
  {
    slug: 'uuid',
    name: 'UUID Generator',
    description: 'Generate v4 UUIDs instantly, in bulk.',
    href: '/uuid/',
    category: 'tool',
  },
  // ── UI Lab (A→Z) ──
  {
    slug: 'liquid-glass',
    name: 'Liquid Glass',
    description: 'Apple-inspired Liquid Glass effect using SVG filters and backdrop-filter.',
    href: '/liquid-glass/',
    category: 'ui',
  },
  {
    slug: 'l-system',
    name: 'L-System',
    description: 'Procedural fractal generation through Lindenmayer rewriting grammars and turtle graphics.',
    href: '/l-system/',
    category: 'ui',
  },
  {
    slug: 'reaction-diffusion',
    name: 'Reaction-Diffusion',
    description: 'Gray-Scott reaction-diffusion simulation running on the GPU via WebGPU compute shaders.',
    href: '/reaction-diffusion/',
    category: 'ui',
  },
  {
    slug: 'mandelbulb',
    name: 'Mandelbulb',
    description: '3D Mandelbulb fractal rendered via GPU ray marching in WebGPU.',
    href: '/mandelbulb/',
    category: 'ui',
  },
  {
    slug: 'lorenz-attractor',
    name: 'Lorenz Attractor',
    description: 'Interactive 3D Lorenz attractor rendered as flowing colored lines in a WebGL2 fragment shader.',
    href: '/lorenz-attractor/',
    category: 'ui',
  },
  {
    slug: 'rossler-attractor',
    name: 'Rössler Attractor',
    description: 'Interactive 3D Rössler attractor rendered as flowing colored lines in a WebGL2 fragment shader.',
    href: '/rossler-attractor/',
    category: 'ui',
  },
  {
    slug: 'tilt-card',
    name: 'Tilt Card',
    description: 'Interactive 3D tilt card with flip animation powered by Motion.',
    href: '/tilt-card/',
    category: 'ui',
  },
  // ── Games (A→Z) ──
  {
    slug: '2048',
    name: '2048',
    description: 'Slide and merge tiles to reach 2048. A classic single-player puzzle game.',
    href: '/2048/',
    category: 'game',
  },
  {
    slug: 'connect-four',
    name: 'Connect Four',
    description: 'Drop discs to connect four in a row. Real-time multiplayer.',
    href: '/connect-four/',
    category: 'game',
  },
  {
    slug: 'dots-and-boxes',
    name: 'Dots & Boxes',
    description: 'Draw lines to complete boxes and outscore your opponent.',
    href: '/dots-and-boxes/',
    category: 'game',
  },
  {
    slug: 'reversi',
    name: 'Reversi',
    description: 'Classic disc-flipping strategy game. Real-time multiplayer.',
    href: '/reversi/',
    category: 'game',
  },
  {
    slug: 'tictactoe',
    name: 'Tic-Tac-Toe',
    description: 'Real-time multiplayer Tic-Tac-Toe. Create a room, share the link, and play.',
    href: '/tictactoe/',
    category: 'game',
  },
  {
    slug: 'wordwolf',
    name: 'Word Wolf',
    description: 'Find the wolf hiding among your friends! A real-time party game for 3-8 players.',
    href: '/wordwolf/',
    category: 'game',
  },
];
